---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: install java on redhat node side 
    dnf:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: install java on debian node side
    apt:
      name: 
      state: present
    when: ansible_os_family=="Debian"