---
- hosts: 172.31.33.207
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install apache2 
    apt:
     name: apache2
     state: present
  - name: copy file into node side
    copy: 
      src: mytestfile
      dest: /home/maha/mytestfile