---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
  - name: install webserver  o node side 
    dnf: 
      name: "{{mywebpack}}" 
      state: present
  - name: start webserver 
    service:
      name: "{{mywebpack}}"
      state: started