---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks: 
  - name: install webserver  on redhat node side 
    dnf: 
      name: "{{mywebpack}}" 
      state: present
  - name: start webserver on redhat node side
    service:
      name: "{{mywebpack}}"
      state: started