---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver  o node side 
    dnf: 
      name: httpd 
      state: present
  - name: start webserver 
    service:
      name: httpd
      state: started